version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11
    steps:
      - checkout
      - run: ./mvnw test
      - run: ./mvnw package
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build .

workflows:
  pr:
    jobs:
      - build
