version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.10
    steps:
      - checkout
      - run: ./mvnw test
      - run: ./mvnw package
      - run: sleep 600

workflows:
  scheduled:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * 1,2,3,4,5 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
