version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.10
    steps:
      - checkout
      - run: ./mvnw test
      - run: ./mvnw package
      - run: sleep 600

workflows:
  scheduled:
    triggers:
      - schedule:
          cron: "* * 1,2,3,4,5,15,16 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
