version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.10
    steps:
      - checkout
      - run: ./mvnw test
      - run: ./mvnw package
      - run: sleep 600

workflows:
  scheduled:
    triggers:
      - schedule:
          cron: "0,10,20,30,40,50 * 1,2,3,4,5,6,7,8,9 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
